version: "3.5"

services:
    db:
      image: mariadb
      volumes:
        - db-data:/var/lib/mysql
      restart: always
      env_file:
        - ./mariadb.env

    wordpress:
      depends_on:
        - db
      image: wordpress:latest
      ports:
        - "8000:80"
      restart: always
      env_file:
        - ./wordpress.env
      environment:
        - WORDPRESS_DB_HOST=db:3306
volumes:
  db-data: