# Work in progress

- name: "Create docker network"
  shell: docker network create -d bridge nginx-proxy

# TODO change this to copy from local
- name: "Get reverse proxy setup"
  shell: git clone https://github.com/The7thSin/Docker.git

- name: "Start Nginx Proxy Container"
  shell: docker-compose pull && docker-compose up -d
  args:
    chdir: Nginx-Proxy-SSL/

# TODO create docker compose script and add to file
# TODO copy from local
-
- name: "Wordpress Setup"
  shell: docker-compose pull && docker-compose up -d
  args:
    chdir: Wordpress/

