# Work in progress

- name: "Create docker network"
  docker_network:
    name: nginx-proxy
    driver: bridge
    state: present

# TODO change this to copy from local
# Get Nginx Proxy from my repo
- git:
    repo: https://github.com/The7thSin/Docker.git
    dest: Docker/

# TODO change path for execution
- name: "Start Nginx Proxy Container"
  shell: docker-compose pull && docker-compose up -d
  args:
    chdir: Docker/Nginx-Proxy-SSL/

- name: "Copy Wordpress Docker Compose"
  copy:
    src: ./files/Wordpress
    dest: /home/$USER/

- name: "Wordpress Setup"
  shell: docker-compose pull && docker-compose up -d
  args:
    chdir: Wordpress/

